// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEBVhzwjzaMYrKbyZVt17EZi0KrNWjcA',
    appId: '1:884909145367:web:831b38723a5dc28b470b52',
    messagingSenderId: '884909145367',
    projectId: 'fir-project-9eb6b',
    authDomain: 'fir-project-9eb6b.firebaseapp.com',
    storageBucket: 'fir-project-9eb6b.appspot.com',
    measurementId: 'G-0HW9J59KR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqDi9dCHb_GKnnwB79WKeYmUc37hGIQw',
    appId: '1:884909145367:android:7b34bb6bc304049f470b52',
    messagingSenderId: '884909145367',
    projectId: 'fir-project-9eb6b',
    storageBucket: 'fir-project-9eb6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstn9SlTxelQSTA0cPrFq0UcNXwgzrzpY',
    appId: '1:884909145367:ios:965a2f9cf9a4abbc470b52',
    messagingSenderId: '884909145367',
    projectId: 'fir-project-9eb6b',
    storageBucket: 'fir-project-9eb6b.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstn9SlTxelQSTA0cPrFq0UcNXwgzrzpY',
    appId: '1:884909145367:ios:965a2f9cf9a4abbc470b52',
    messagingSenderId: '884909145367',
    projectId: 'fir-project-9eb6b',
    storageBucket: 'fir-project-9eb6b.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
